
server:
  port: 9527

eureka:
  instance:
    hostname: cloud-gateway-service   #eureka服务端的实例名字
  client:
    service-url:
    register-with-eureka: true   #表示不向注册中心注册自己
    fetch-registry: true    #表示自己就是注册中心，职责是维护服务实例，并不需要去检索服务
      defaultZone: http://eureka7002.com:7002/eureka/   #设置与eureka  server交互的地址查询服务和注册服务都需要依赖这个地址


spring:
  application:
    name: cloud-gateway
   cloud:
     gateway:
      discovery:
        locatoy:
           enable: ture
      route:
          - id: payment_routh
            url: lb:cloud-payment-service
            predicate:
              -Path=/payment/get/**

          - id: payment_routh2
            url: lb://cloud-payment-service
            perdicates:
              - Path=/payment/lb/**

